#
# application.yml
#
# This will become the base profile for the "common settings"
# All settings here may be overriden by profile-specific properties in application-{profile}.yml
# 


# Server settings
server:
  port: 8080


# app name and build version updated during build process from Maven properties.
info:
  app:
    name: '@project.artifactId@'
  build:
    version: '@project.version@'
