#
# application-prod.yml
#
# This is the "prod" profile by following the naming pattern: application-{profile}.yml
# 


# Spring configuration
spring:
  profiles:
    active: prod                              # profiles to activated, separated by comma (,)
    include:
    - mysql
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: mysql                           # database platform
    driverClassName: com.mysql.cj.jdbc.Driver # JDBC Driver
    url: jdbc:mysql://mysql:3306/testdb       # JDBC URL, e.g. jdbc:mysql://localhost:3306/testdb
    username: myuser                          # JDBC Username
    password: mypassword                      # JDBC Password
  flyway:                                     # flyway
    schemas:
    - testdb
  jmx:
    enabled: true

# Actuator Configuration
# Ref: https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html
management:
  endpoints:
    enabled-by-default: false                 # defaults it to false and expose only what you want
    web:
      exposure:
        include:
        - health
        - prometheus
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    flyway:
      enabled: true
    loggers:
      enabled: true
    prometheus:
      enabled: true
    metrics:
      enabled: true
    env:
      enabled: true
