apiVersion: v1
kind: Secret
metadata:
  name: mysql
data:
  db_password: bXlwYXNzd29yZA==     # mypassword
  db_username: bXl1c2Vy             # myuser
  root_password: bXlwYXNzd29yZA==   # mypassword
